[tools]
rust = "stable"

[tasks.run-cli]
alias = "cli"
run = "cargo run --bin cli"

[tasks.run-server]
alias = "server"
run = "cargo run --bin server"


[tasks.build-release]
alias = "br"
run = "cargo build --release"
