[tools]
rust = "stable"

[tasks.run-cli]
alias = "cli"
run = "cargo run --bin cli"

[tasks.run-server]
alias = "server"
run = "cargo run --bin server"


[tasks.build-release]
alias = "br"
run = """
cargo build --release
cross build --target x86_64-unknown-linux-gnu  --release
cross build --target x86_64-pc-windows-gnu --release
"""
